services:
  nginx:
    image: nginx:alpine
    container_name: nginx_api_masjid
    restart: always
    expose:
      - "80"
    volumes:
      - ./mosque-announcement-api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - masjid-net

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel_masjid
    restart: always
    volumes:
      - ./mosque-announcement-api:/var/www
    networks:
      - masjid-net

networks:
  masjid-net:
    external: true
