version: "3.8"

services:
  assets:
    image: nginx:alpine
    container_name: assets_server_masjid
    restart: always
    expose:
      - "80"
    volumes:
      - ../api-mosque-announcement/mosque-announcement-api/storage/app/public:/usr/share/nginx/html/storage
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - masjid-net


networks:
  masjid-net:
    external: true
