services:
  nginx_gateway:
    image: nginx:alpine
    container_name: nginx_gateway_masjid
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - masjid-net
    restart: unless-stopped

networks:
  masjid-net:
    external: true
